#!/usr/bin/env bash

git fetch origin master -q
COMMIT=$(git rev-parse --short origin/master)
echo "Latest Commit:"
echo
git --no-pager log --decorate=short -n1 origin/master --pretty=format:"%h - %an, %ar : %s"
echo
echo
read -p "Want to rollout? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo
    gh release create deploy-$COMMIT --target master --title "Release $COMMIT" --notes ""
    echo "Created Release $COMMIT with Tag deploy-$COMMIT"
fi
