#!/usr/bin/env bash
# extract: extract most know archives with one command
# usage: extract <archive> [archives...]
# based on: https://github.com/ohmybash/oh-my-bash/blob/master/lib/base.sh#L88

help() {
    echo >&2 "Usage: $(basename "$0") <archive> [archives...]

Extracts most known archive formats automatically.

Supported Formats:
  .tar.bz2, .tbz2   - bzip2 compressed tar
  .tar.gz, .tgz     - gzip compressed tar
  .tar.xz, .txz     - xz compressed tar
  .tar.zst          - zstd compressed tar
  .tar              - tar archive
  .rar              - rar archive
  .zip              - zip archive
  .bz2              - bzip2 compressed file
  .gz               - gzip compressed file
  .xz               - xz compressed file
  .zst              - zstd compressed file
  .Z                - compress archive
  .7z               - 7zip archive

Options:
  -h, --help        Show this help message and exit

Example:
  $(basename "$0") file.tar.gz
  $(basename "$0") archive.zip archive.tar.xz"
}

if [[ $# -eq 0 || "$*" =~ (-h|--help) ]]; then
    help
    exit 0
fi

while [[ $# -gt 0 ]]; do
    if [[ -f "$1" ]]; then
        case "$1" in
        *.tar.bz2 | *.tbz2) tar xjf "$1" ;;
        *.tar.gz | *.tgz) tar xzf "$1" ;;
        *.tar.xz | *.txz) tar xJf "$1" ;;
        *.tar.zst) tar --zstd -xf "$1" ;;
        *.tar) tar xf "$1" ;;
        *.rar) rar x "$1" ;;
        *.zip) unzip "$1" ;;
        *.bz2) bunzip2 "$1" ;;
        *.gz) gunzip "$1" ;;
        *.xz) xz -dk "$1" ;;
        *.zst) zstd -d "$1" ;;
        *.Z) uncompress "$1" ;;
        *.7z) 7z x "$1" ;;
        *)
            echo "'$1' cannot be extracted. Unknown archive format." ""
            help
            exit 1
            ;;
        esac
    else
        echo "$(basename "$0"): '$1' is not a valid file"
        exit 2
    fi
    shift
done
