#!/usr/bin/env bash
# loop: continously re-execute an arbitrary command
# usage: loop <command> <args...>

help() {
  >&2 echo "Usage: $(basename "$0") <command> <args...>

Continuously re-execute an arbitrary command. Use Ctrl+C to exit.

Options:
  -h, --help    Show this help message and exit

Arguments:
  <command>     Command to execute continuously.
  <args...>     Additional arguments for the command.

Example:
  $(basename "$0") kubectl get pods -A"
}

if [[ $# -lt 1 || "$@" =~ (-h|--help) ]]; then
    help
    exit 0
fi


if fish -c "functions -q $1" &>/dev/null; then
    set -- fish -c "$*"
elif [[ ! -x "$(command -v $1)" ]]; then
    >&2 echo "$(basename "$0"): '$1' command not found"
    help
    exit 2
fi

tmpfile=$(mktemp)

cleanup() {
    rm -f "$tmpfile"
    exit 0
}

trap cleanup SIGINT

while true; do
    "$@" > "$tmpfile" 2>&1
    clear
    cat "$tmpfile"
    sleep 1
done
