#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(echo "latte frappe macchiato mocha" | tr ' ' '\n' | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

if [[ -x "$(command -v alacritty)" ]]; then
    ln -sf ~/.config/alacritty/themes/catppuccin-$selected.toml ~/.config/alacritty/theme.toml
    touch ~/.config/alacritty/alacritty.toml
fi

if [[ ! -z $TMUX ]] && [[ ! -z $(pgrep tmux) ]]; then
    tmux set -g @catppuccin_flavour $selected
    tmux source-file ~/.tmux.conf
fi
