---
- name: Include macOS tasks
  when: ansible_system == "Darwin"
  ansible.builtin.include_tasks: macos.yml

- name: Include Linux tasks
  when: ansible_system == "Linux"
  ansible.builtin.include_tasks: linux.yml

- name: Install plugins through krew
  ansible.builtin.command: "kubectl krew install cond ctx foreach ns tree"
  environment:
    PATH: "{{ ansible_env.HOME }}/.local/bin:{{ ansible_env.PATH }}"

- name: Create symbolic link for config
  ansible.builtin.file:
    src: "{{ role_path }}/files/k9s"
    dest: "{{ xdg_config_home }}/k9s"
    state: link

- name: Ensure ~/.config/k9s/skins exists
  ansible.builtin.file:
    path: "{{ xdg_config_home }}/k9s/skins"
    state: directory
    mode: "0755"

- name: Download Catppuccin theme for k9s
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/catppuccin/k9s/refs/heads/main/dist/catppuccin-mocha.yaml"
    dest: "{{ xdg_config_home }}/k9s/skins/catppuccin-mocha.yaml"
    mode: "0644"

- name: Download kubectl aliases
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/felix-kaestner/kubectl-aliases/refs/heads/custom/.kubectl_aliases.fish"
    dest: "{{ ansible_env.HOME }}/.kubectl.fish"
    mode: "0644"
