complete -c k -n 'test (count (commandline -xpc)) -eq 1' -a dbg -d "Debug a pod"
complete -c k -n 'test (count (commandline -xpc)) -eq 1' -a dashboard -d "Open dashboard"
complete -c k -n 'test (count (commandline -xpc)) -eq 1' -a cluster-name -d "Print cluster name"
complete -c k -n 'test (count (commandline -xpc)) -eq 1' -a containers -d "Print name(s) of the container(s) within a pod"
complete -c k -n 'test (count (commandline -xpc)) -eq 1' -a tree -d "Show sub-resources of the Kubernetes object"
complete -c k -n 'test (count (commandline -xpc)) -eq 1' -a cond -d "View Kubernetes resource conditions"
complete -c k -n 'test (count (commandline -xpc)) -eq 1' -a ctx -d "Switch to context"
complete -c k -n 'test (count (commandline -xpc)) -eq 1' -a ns -d "Switch to namespace"
complete -c k -n 'test (count (commandline -xpc)) -eq 1' -a rf -d "Remove finalizers"
complete -c k -n 'test (count (commandline -xpc)) -eq 1' -a pause -d "Pause reconciliation"
complete -c k -n 'test (count (commandline -xpc)) -eq 1' -a unpause -d "Unpause reconciliation"

complete -c k -n "__fish_seen_subcommand_from dbg" -xa "(k get pod -o name | awk -F '/' '{print \$2}')"
complete -c k -n "__fish_seen_subcommand_from containers" -xa "(k get pod -o name | awk -F '/' '{print \$2}')"
complete -c k -n '__fish_seen_subcommand_from cond' -xa "(complete -C (string replace 'k cond' 'kubectl get' (commandline)) | awk '{print \$1}')"
complete -c k -n '__fish_seen_subcommand_from tree' -xa "(complete -C (string replace 'k tree' 'kubectl get' (commandline)) | awk '{print \$1}')"
complete -c k -n "__fish_seen_subcommand_from foreach" -f -a "(k config get-contexts -o name)"
complete -c k -n "__fish_seen_subcommand_from ctx" -f -a "(k config get-contexts -o name)"
complete -c k -n "__fish_seen_subcommand_from ctx" -s d -d "Delete context" -xa "(k config get-contexts -o name)"
complete -c k -n "__fish_seen_subcommand_from ctx" -s c -l current -d "Show current context"
complete -c k -n "__fish_seen_subcommand_from ctx" -s u -l unset -d "Unset current context"
complete -c k -n "__fish_seen_subcommand_from ctx" -s h -l help -d "Show help message"
complete -c k -n "__fish_seen_subcommand_from ns" -s c -l current -d "Show current context"
complete -c k -n "__fish_seen_subcommand_from ns" -s h -l help -d "Show help message"
complete -c k -n "__fish_seen_subcommand_from ns" -f -a "(k get namespace -o name | awk -F '/' '{print \$2}')"
complete -c k -n '__fish_seen_subcommand_from rf' -xa "(complete -C (string replace 'k rf' 'kubectl get' (commandline)) | awk '{print \$1}')"
complete -c k -n '__fish_seen_subcommand_from pause' -xa "(complete -C (string replace 'k pause' 'kubectl get' (commandline)) | awk '{print \$1}')"
complete -c k -n '__fish_seen_subcommand_from unpause' -xa "(complete -C (string replace 'k unpause' 'kubectl get' (commandline)) | awk '{print \$1}')"

# Label selector shorthands from https://github.com/ironcore-dev/network-operator
complete -c k -s d -l device -d "Filter by device name"
complete -c k -s s -l device-serial -d "Filter by device serial"
complete -c k -s a -l aggregate -d "Filter by aggregate interface name"
complete -c k -s r -l routed-vlan -d "Filter by routed-vlan interface name"
complete -c k -s e -l evi -d "Filter by evi name"
complete -c k -s v -l vrf -d "Filter by vrf name"

# Label selector shorthands from https://github.com/sapcc/helm-charts
complete -c k -s S -l service -d "Filter by SAP Cloud Infrastructure service"
complete -c k -s g -l support-group -d "Filter by SAP Cloud Infrastructure support-group"
