complete -c k -n 'test (count (commandline -xpc)) -eq 1' -a dbg -d "Debug a pod"
complete -c k -n 'test (count (commandline -xpc)) -eq 1' -a dashboard -d "Open dashboard"
complete -c k -n 'test (count (commandline -xpc)) -eq 1' -a cluster-name -d "Print cluster name"
complete -c k -n 'test (count (commandline -xpc)) -eq 1' -a containers -d "Print name(s) of the container(s) within a pod"
complete -c k -n 'test (count (commandline -xpc)) -eq 1' -a tree -d "Show sub-resources of the Kubernetes object"
complete -c k -n 'test (count (commandline -xpc)) -eq 1' -a cond -d "View Kubernetes resource conditions"
complete -c k -n 'test (count (commandline -xpc)) -eq 1' -a ctx -d "Switch to context"
complete -c k -n 'test (count (commandline -xpc)) -eq 1' -a ns -d "Switch to namespace"

complete -c k -n "__fish_seen_subcommand_from dbg" -xa "(k get pod -o name | awk -F '/' '{print \$2}')"
complete -c k -n "__fish_seen_subcommand_from containers" -xa "(k get pod -o name | awk -F '/' '{print \$2}')"
complete -c k -n '__fish_seen_subcommand_from cond' -xa "(complete -C (string replace 'k cond' 'kubectl get' (commandline)) | awk '{print \$1}')"
complete -c k -n '__fish_seen_subcommand_from tree' -xa "(complete -C (string replace 'k tree' 'kubectl get' (commandline)) | awk '{print \$1}')"
complete -c k -n "__fish_seen_subcommand_from foreach" -f -a "(k config get-contexts -o name)"
complete -c k -n "__fish_seen_subcommand_from ctx" -f -a "(k config get-contexts -o name)"
complete -c k -n "__fish_seen_subcommand_from ctx" -s d -d "Delete context" -xa "(k config get-contexts -o name)"
complete -c k -n "__fish_seen_subcommand_from ctx" -s c -l current -d "Show current context"
complete -c k -n "__fish_seen_subcommand_from ctx" -s u -l unset -d "Unset current context"
complete -c k -n "__fish_seen_subcommand_from ctx" -s h -l help -d "Show help message"
complete -c k -n "__fish_seen_subcommand_from ns" -s c -l current -d "Show current context"
complete -c k -n "__fish_seen_subcommand_from ns" -s h -l help -d "Show help message"
complete -c k -n "__fish_seen_subcommand_from ns" -f -a "(k get namespace -o name | awk -F '/' '{print \$2}')"
