---
- name: Install MicroK8s
  when: ansible_system == "Darwin"
  community.general.homebrew:
    name: "ubuntu/microk8s/microk8s"
    state: present

- name: Install MicroK8s
  when: ansible_system == "Linux"
  block:
    - name: Check if Snap is available
      ansible.builtin.shell: command -v snap
      register: snap_path
      changed_when: false

    - name: Install MicroK8s via Snap
      when: snap_path.rc == 0
      community.general.snap:
        name: "microk8s"
        state: present
        classic: true
        channel: "1.32"
      become: true

    - name: Add user to microk8s group
      when: snap_path.rc == 0
      ansible.builtin.user:
        name: "{{ user }}"
        groups: microk8s
        append: yes
      become: true
