[general]
import = [ "theme.toml" ]

[font]
size = 14

[font.normal]
family = "JetBrainsMono Nerd Font"

[window]
decorations = "None"
startup_mode = "Maximized"
option_as_alt = "OnlyRight"
dynamic_padding = true

[selection]
save_to_clipboard = true

[[hints.enabled]]
command = "open"
hyperlinks = true
post_processing = true
mouse = { enabled = true }
binding = { key = "O", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[[hints.enabled]]
regex = '"\w[\w-]+\/[\w.-]+"'
command = { program = "bash", args = [ "-c", 'open https://github.com/${1//\"/}', "--" ] }
binding = { key = "G", mods = "Control|Shift" }
mouse = { enabled = true }

[[hints.enabled]]
regex = "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"
action = "Copy"
binding = { key = "U", mods = "Control|Shift" }

[[hints.enabled]]
regex = "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"
action = "Paste"
mouse = { enabled = true }

[[hints.enabled]]
regex = "[0-9a-f]{40}|[0-9a-f]{12}|[0-9a-f]{7,8}"
action = "Copy"
binding = { key = "H", mods = "Control|Shift" }

[[hints.enabled]]
regex = "[0-9a-f]{40}|[0-9a-f]{12}|[0-9a-f]{7,8}"
action = "Paste"
mouse = { enabled = true }

[[hints.enabled]]
regex = "(\\d{1,3}\\.){3}\\d{1,3}(:\\d{1,5})?"
action = "Copy"
binding = { key = "I", mods = "Control|Shift" }

[[hints.enabled]]
regex = "(\\d{1,3}\\.){3}\\d{1,3}(:\\d{1,5})?"
action = "Paste"
mouse = { enabled = true }

[[hints.enabled]]
regex = "[^ ]+\\.[^ ]+:\\d+(:\\d+)?"
action = "Copy"
binding = { key = "L", mods = "Control|Shift" }

[[hints.enabled]]
regex = "[^ ]+\\.[^ ]+:\\d+(:\\d+)?"
action = "Paste"
mouse = { enabled = true }

[[hints.enabled]]
regex = "(/[\\w.-]+)+"
action = "Copy"
binding = { key = "F", mods = "Control|Shift" }

[[hints.enabled]]
regex = "(/[\\w.-]+)+"
action = "Paste"
mouse = { enabled = true }
