---
- name: Include vars from local.yml
  when: "(role_path + '/vars/local.yml') is file"
  ansible.builtin.include_vars:
    file: "{{ role_path }}/vars/local.yml"

- name: Create symbolic link for config
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "{{ xdg_config_home }}/git"
    state: link

- name: Create ~/.config/git/config.local
  ansible.builtin.template:
    src: "{{ role_path }}/templates/config.local.j2"
    dest: "{{ xdg_config_home }}/git/config.local"
    force: false

- name: Install Git LFS
  ansible.builtin.package:
    name: git-lfs
    state: present
