---
- name: Install go
  when: ansible_distribution != "Ubuntu"
  ansible.builtin.package:
    name: "{{ 'go' if ansible_system == 'Darwin' else 'golang' }}"
    state: present
  become: "{{ ansible_system == 'Linux' }}"

- name: Install go
  when: ansible_distribution == "Ubuntu"
  community.general.snap:
    name: "go"
    state: present
    classic: true
  become: true

- name: Install go tools
  when: ansible_system == "Darwin"
  community.general.homebrew:
    name:
      - "caarlos0/tap/timer"
      - "golangci-lint"
      - "goreleaser"
      - "glow"
      - "fx"

- name: Get GOOS environment variable
  ansible.builtin.command: go env GOOS
  register: goos

- name: Get GOARCH environment variable
  ansible.builtin.command: go env GOARCH
  register: goarch

- name: Download kubebuilder
  ansible.builtin.get_url:
    url: "https://go.kubebuilder.io/dl/latest/{{ goos.stdout }}/{{ goarch.stdout }}"
    dest: "{{ ansible_env.HOME }}/.local/bin/kubebuilder"
    mode: "0755"

- name: Install goimports
  ansible.builtin.command: go install golang.org/x/tools/cmd/goimports@latest
  environment:
    GOPATH: "{{ ansible_env.HOME }}/.go"
    PATH: "{{ ansible_env.HOME }}/.go/bin:{{ ansible_env.PATH }}"
  args:
    creates: "{{ ansible_env.HOME }}/.go/bin/goimports"

- name: Install govulncheck
  ansible.builtin.command: go install golang.org/x/vuln/cmd/govulncheck@latest
  environment:
    GOPATH: "{{ ansible_env.HOME }}/.go"
    PATH: "{{ ansible_env.HOME }}/.go/bin:{{ ansible_env.PATH }}"
  args:
    creates: "{{ ansible_env.HOME }}/.go/bin/govulncheck"

- name: Install kind
  ansible.builtin.command: go install sigs.k8s.io/kind@latest
  environment:
    GOPATH: "{{ ansible_env.HOME }}/.go"
    PATH: "{{ ansible_env.HOME }}/.go/bin:{{ ansible_env.PATH }}"
  args:
    creates: "{{ ansible_env.HOME }}/.go/bin/kind"

- name: Install kind fish completion
  ansible.builtin.command: "kind completion fish > {{ ansible_env.HOME }}/.local/share/fish/vendor_completions.d/kind.fish"
  environment:
    GOPATH: "{{ ansible_env.HOME }}/.go"
    PATH: "{{ ansible_env.HOME }}/.go/bin:{{ ansible_env.PATH }}"

- name: Set go toolchain to local
  ansible.builtin.command: go env -w GOTOOLCHAIN=local
  environment:
    GOPATH: "{{ ansible_env.HOME }}/.go"
    PATH: "{{ ansible_env.HOME }}/.go/bin:{{ ansible_env.PATH }}"
