#!/usr/bin/env bash

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." &> /dev/null && pwd)"

set -eu
cd "$DIR" || exit 1

info () {
  printf "\r  [ \033[00;34m..\033[0m ] $1\n"
}


if [ -f /etc/os-release ]
then
    awk -F= '/^ID=/{print $2}' /etc/os-release | grep -Eiq 'debian|ubuntu|mint'
    if [ $? -eq 0 ]
    then
        sudo apt update
        sudo apt upgrade -y
    fi
fi


# find the installers and run them iteratively
find . -name install.sh | while read installer ; do info "Executing ${installer}"; sh -c "${installer}" ; done