---
- name: Install pnpm
  ansible.builtin.shell: curl -fsSL https://get.pnpm.io/install.sh | ENV="$HOME/.shrc" SHELL="$(command -v sh)" sh -
  args:
    creates: "{{ ansible_env.HOME }}/.local/share/pnpm"

- name: Delete $HOME/.shrc
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.shrc"
    state: absent

- name: Install Node.js
  ansible.builtin.shell: pnpm env use --global lts
  environment:
    PNPM_HOME: "{{ ansible_env.HOME }}/.local/share/pnpm"
    PATH: "{{ ansible_env.HOME }}/.local/share/pnpm:{{ ansible_env.PATH }}"

- name: Install pnpm fish completion
  ansible.builtin.shell: "pnpm completion fish > {{ ansible_env.HOME }}/.local/share/fish/vendor_completions.d/pnpm.fish"
  environment:
    PNPM_HOME: "{{ ansible_env.HOME }}/.local/share/pnpm"
    PATH: "{{ ansible_env.HOME }}/.local/share/pnpm:{{ ansible_env.PATH }}"

- name: Install tldr
  ansible.builtin.shell: pnpm install --global tldr
  environment:
    PNPM_HOME: "{{ ansible_env.HOME }}/.local/share/pnpm"
    PATH: "{{ ansible_env.HOME }}/.local/share/pnpm:{{ ansible_env.PATH }}"

- name: Install ntn
  ansible.builtin.shell: pnpm install --global ntn
  environment:
    PNPM_HOME: "{{ ansible_env.HOME }}/.local/share/pnpm"
    PATH: "{{ ansible_env.HOME }}/.local/share/pnpm:{{ ansible_env.PATH }}"

- name: Install ntn fish completion
  ansible.builtin.shell: "ntn completions fish > {{ ansible_env.HOME }}/.local/share/fish/vendor_completions.d/ntn.fish"
  environment:
    PNPM_HOME: "{{ ansible_env.HOME }}/.local/share/pnpm"
    PATH: "{{ ansible_env.HOME }}/.local/share/pnpm:{{ ansible_env.PATH }}"

- name: Install agent-browser
  ansible.builtin.shell: pnpm install --global agent-browser
  environment:
    PNPM_HOME: "{{ ansible_env.HOME }}/.local/share/pnpm"
    PATH: "{{ ansible_env.HOME }}/.local/share/pnpm:{{ ansible_env.PATH }}"

- name: Install playwright-cli
  ansible.builtin.shell: pnpm install --global @playwright/cli
  environment:
    PNPM_HOME: "{{ ansible_env.HOME }}/.local/share/pnpm"
    PATH: "{{ ansible_env.HOME }}/.local/share/pnpm:{{ ansible_env.PATH }}"

# https://skills.sh
- name: Install skills CLI
  ansible.builtin.shell: pnpm install --global skills
  environment:
    PNPM_HOME: "{{ ansible_env.HOME }}/.local/share/pnpm"
    PATH: "{{ ansible_env.HOME }}/.local/share/pnpm:{{ ansible_env.PATH }}"

- name: "Install skills"
  ansible.builtin.shell: >
    skills add "https://github.com/{{ item.repo }}" {{ '--skill "' + item.skill + '"' if item.skill is defined else '' }} -g -a universal claude-code pi antigravity -y
  environment:
    PNPM_HOME: "{{ ansible_env.HOME }}/.local/share/pnpm"
    PATH: "{{ ansible_env.HOME }}/.local/share/pnpm:{{ ansible_env.PATH }}"
  loop:
    - { repo: "anthropics/skills", skill: "doc-coauthoring" }
    - { repo: "anthropics/skills", skill: "pdf" }
    - { repo: "anthropics/skills", skill: "docx" }
    - { repo: "anthropics/skills", skill: "pptx" }
    - { repo: "anthropics/skills", skill: "xlsx" }
    - { repo: "anthropics/skills", skill: "skill-creator" }
    - { repo: "vercel-labs/skills", skill: "find-skills" }
    - { repo: "vercel-labs/agent-browser", skill: "agent-browser" }
    - { repo: "github/awesome-copilot", skill: "git-commit" }
    - { repo: "github/awesome-copilot", skill: "excalidraw-diagram-generator" }
    - { repo: "github/awesome-copilot", skill: "refactor" }
    - { repo: "github/awesome-copilot", skill: "github-issues" }
    - { repo: "github/awesome-copilot", skill: "memory-merger" }
    - { repo: "microsoft/playwright-cli", skill: "playwright-cli" }
    - { repo: "mattpocock/skills", skill: "caveman" }
    - { repo: "mattpocock/skills", skill: "grill-me" }
    - { repo: "samber/cc-skills-golang" }
    - { repo: "kepano/obsidian-skills" }
    - { repo: "github/gh-stack" }
    - { repo: "makenotion/skills" }
