import = [
    "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
size = 13

[font.normal]
family = "JetBrainsMono Nerd Font"

[font.bold]
family = "JetBrainsMono Nerd Font"

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"

[window]
decorations = "None"
startup_mode = "Maximized"
option_as_alt = "OnlyLeft"

[selection]
save_to_clipboard = true
