import = [
    "~/.config/alacritty/theme.toml"
]

[font]
size = 12.45

[font.normal]
family = "JetBrainsMono Nerd Font"

[window]
decorations = "None"
startup_mode = "Maximized"
option_as_alt = "OnlyLeft"
dynamic_padding = true

[selection]
save_to_clipboard = true

[[hints.enabled]]
command = "open"
hyperlinks = true
post_processing = true
mouse = { enabled = true }
binding = { key = "U", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[[hints.enabled]]
regex = "[A-Z]+-\\d+"
command = { program = "bash", args = [ "-c", "open https://aboutyou.atlassian.net/browse/${1}", "--" ] }
binding = { key = "T", mods = "Control|Shift" }
mouse = { enabled = true }

[[hints.enabled]]
regex = '"\w[\w-]+\/[\w.-]+"'
command = { program = "bash", args = [ "-c", 'open https://github.com/${1//\"/}', "--" ] }
binding = { key = "G", mods = "Control|Shift" }
mouse = { enabled = true }

[[hints.enabled]]
regex = "[a-f0-9]{40}|[a-f0-9]{7,8}"
action = "Copy"
binding = { key = "H", mods = "Control|Shift" }

[[hints.enabled]]
regex = "(\\d{1,3}\\.){3}\\d{1,3}(:\\d{1,5})?"
action = "Copy"
binding = { key = "I", mods = "Control|Shift" }

[[hints.enabled]]
regex = "[^ ]+\\.[^ ]+:\\d+(:\\d+)?"
action = "Copy"
binding = { key = "L", mods = "Control|Shift" }

