import = [
    "~/.config/alacritty/theme.toml"
]

[font]
size = 12.45

[font.normal]
family = "JetBrainsMono Nerd Font"

[window]
decorations = "None"
startup_mode = "Maximized"
option_as_alt = "OnlyLeft"
dynamic_padding = true

[selection]
save_to_clipboard = true
