---
- name: Install alacritty
  ansible.builtin.package:
    name: "alacritty"
    state: present
  become: "{{ ansible_system == 'Linux' }}"

- name: Create symbolic link for config
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "{{ xdg_config_home }}/alacritty"
    state: link

- name: Download Catppuccin theme for Alacritty
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/catppuccin/alacritty/refs/heads/main/catppuccin-mocha.toml"
    dest: "{{ xdg_config_home }}/alacritty/theme.toml"
    mode: "0644"
