---
- name: Install Lima
  community.general.homebrew:
    name: "lima"
    state: present

- name: Define Lima arguments
  ansible.builtin.set_fact:
    # https://github.com/rancher-sandbox/rancher-desktop/blob/main/pkg/rancher-desktop/backend/lima.ts#L570-L573
    lima_args: "--vm-type=vz --rosetta --mount=~/Developer:w --mount=/var/folders:w --mount=/tmp/lima:w --mount-type=virtiofs --mount-inotify --memory=16"

- name: Create "default" lima-vm instance
  ansible.builtin.shell: "limactl create {{ lima_args }} --name=default template://default 2>/dev/null || true"

- name: Create "docker" lima-vm instance
  ansible.builtin.shell: "limactl create {{ lima_args }} --network=vzNAT --name=docker template://docker-rootful 2>/dev/null || true"

- name: Create "k8s" lima-vm instance
  ansible.builtin.shell: "limactl create {{ lima_args }} --name=k8s template://k8s 2>/dev/null || true"

- name: Enable nested virtualization and ssh agent forwarding for vz lima instances
  ansible.builtin.shell: |
    for vm in default docker k8s; do
        limactl edit --set '.ssh.forwardAgent=true | .nestedVirtualization=true' $vm
    done
