#!/bin/sh

if git diff --cached | grep '!nocommit' >/dev/null 2>&1; then
    echo 'Trying to commit non-committable code.'
    echo 'Remove the !nocommit string and try again.'
    exit 1
fi

# Run local pre-commit hooks, if present
PROJECT_DIR=$(git rev-parse --show-toplevel)
if [ -x "${PROJECT_DIR}/.git/hooks/pre-commit" ]; then
    "${PROJECT_DIR}/.git/hooks/pre-commit" "$@"
fi

# vim: syn=sh ft=sh
